### PR TITLE
chore: ns7 updates and angular 10 updates

### PR DESCRIPTION
**Pull request by NathanWalker**

### CODE REVIEW

**Comment by farfromrefug** [comment]
Thanks Nathan but I won't accept it that way. It is already N 7 compatible. What you are bringing is actually angular 10. And as l told you once I don't want another node_modules inside the angular folder. It is too messy.
I will have to find a better way to do it. 
In this PR there a lot of changes not related to that, some I even don't want. 
Would you like to open a PR with only the angular part?

**Comment by NathanWalker** [comment]
@farfromrefug this is just to get a published version out that developers can use right now - this was blocking a test Igor was working on. We would appreciate you publishing a build with these changes however can keep it on PR here as I do have an improved angular build integration that I didn't have time to add here yet but will over next couple days. In meantime, please publish a working build.

**Comment by farfromrefug** [comment]
A test on what angular? It is already published on N 7 and should be compatible. What was the issue Igor was facing? There are too many parts in this PR.

**Comment by NathanWalker** [comment]
It doesn't work currently - the latest published does not work with NS 7 (still had deep import path's and nativeclass decorations were incorrect due to invalid path in the tsconfig plugins in addition to a maximum call stack trace due to invalid ios .class() setup).

**Comment by NathanWalker** [comment]
I was able to publish a 4.0.0 under `rc` for now - I'll get the angular build adjusted here in next couple days.

**Comment by farfromrefug** [comment]
The good process of handling this would be to create issues so that everyone can benefit from the understanding of the issue. Going and creating PR which contains so many thing is not the right way to go.
It is also showing quite a lack of respect (like publishing without even waiting for my opinion) for the plugin dev (i for this one).
Deeply disappointed!

**Pull request closed without merging**
